on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
    contents: write

jobs:
  update:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          make
